# Generated by Django 4.0.6 on 2024-03-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rename_message_message_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
