# Generated by Django 4.0.6 on 2024-03-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_roommembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
