# Generated by Django 5.0.3 on 2024-03-26 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_room_created_by_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
    ]
